services:
  app:
    build: .
    container_name: flask-app
    restart: always
    environment:
      - ENVIRONMENT=production

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
